//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crediyi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LineaCabezal
    {
        public string Serie { get; set; }
        public int Numero { get; set; }

        [DisplayName("ID Línea")]
        public int IdLinea { get; set; }

        [DisplayName("ID Producto")]
        public int IdProd { get; set; }
        public int Cantidad { get; set; }

       // public int ImportexLinea { get; }

        public virtual CompraCabezal CompraCabezal { get; set; }
        public virtual Productos Productos { get; set; }



        private int impLinea;

        [DisplayName("Importe Linea")]
        public int ImpLinea
        {
            get { return ImporteLinea(); }
        }

        public int ImporteLinea()
        {
            if (Productos != null)
            {
                impLinea += this.Cantidad * (Convert.ToInt32(this.Productos.Importe));
            }
           
            return impLinea;
        }


        //validar Contenido de Objeto
        public void Validar()
        {

            if (this.IdLinea <= 0)
                throw new Exception("El Id de Línea debe ser positivo");
            if (this.Productos == null)
                throw new Exception("Debe seleccionar un producto");
            if (this.Cantidad <= 0)
                throw new Exception("Cantidad debe ser un valor positivo");

        }

    }
}
