//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crediyi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Productos
    {
        [DisplayName("ID Producto")]
        public int IdProd { get; set; }

        [DisplayName("Producto")]
        public string DscProd { get; set; }
        public decimal Importe { get; set; }


        //validar Contenido de Objeto
        public void Validar()
        {

            if (this.IdProd <= 0)
                throw new Exception("El Id de Producto debe ser positivo");
            // debe existir en tipodoc
            if (this.DscProd.Trim().Length < 5 && this.DscProd.Trim().Length > 40)
                throw new Exception("La descripción debe contener al menos 6 caracteres y máximo 40.");
            if (this.Importe <= 0)
                throw new Exception("El Importe debe ser un valor positivo");

        }

    }
}
