//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crediyi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TiposDocumentos
    {
        [DisplayName("ID Tipo Documento")]
        public int IdTipoDoc { get; set; }

        [DisplayName("Tipo Documento")]
        public string DscTipoDoc { get; set; }


        //validar Contenido de Objeto
        public void Validar()
        {

            if (this.IdTipoDoc <= 0)
                throw new Exception("El Id de Tipo Documento debe ser positivo");
            // debe existir en tipodoc
            if (this.DscTipoDoc.Trim().Length < 5 && this.DscTipoDoc.Trim().Length > 25)
                throw new Exception("La descripción debe contener al menos 2 caracteres y máximo 25.");
           
        }


    }
}
