//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crediyi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        [DisplayName("Usuario")]
        public string Usu { get; set; }

        [DisplayName("Contraseña")]
        public string Pass { get; set; }

        [DisplayName("Nombre Completo")]
        public string NomUsu { get; set; }


    }
}
